# Generated by Django 5.1.4 on 2025-01-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_emergencycare'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycare',
            name='location',
            field=models.CharField(default='Unknown', max_length=25),
        ),
    ]
