# Generated by Django 5.1.4 on 2025-01-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_emergencycare_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='online_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('gaenocology', 'gaenocology'), ('consultation', 'consultation'), ('patient_review', 'patient_review')], max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='emergencycare',
            name='location',
            field=models.CharField(default='', max_length=25),
        ),
    ]
